apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: configmap-watch-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-boot-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-watch-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: spring-boot-sa
  namespace: default
roleRef:
  kind: Role
  name: configmap-watch-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-example
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leader-example
  template:
    metadata:
      labels:
        app: leader-example
    spec:
      serviceAccountName: spring-boot-sa
      containers:
      - name: leader-example
        image: leader_example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        env:
        - name: KUBERNETES_LEADER_ELECTION
          value: "true"
